---

- name: Gather EC2 facts
  action: ec2_facts

- name: Check whether swap is active
  shell: "cat /proc/meminfo | awk '/SwapTotal/ {print $2}'"
  register: swapstatus
  changed_when: false

- include: needs_swap.yml
  when: swapstatus.stdout == "0"
