---

## Tasks that are only run when the system does not yet have swap activated.
#

# EC2 Instance Store volumes are only created and managed for instance types
# that have Instance Store volumes.  (Which excludes t2 and m4.)
# Instances that don't have Instance Store volumes will have the /swap
# directory created on the root volume.

- name: Ensure state of /swap directory
  file: path=/swap state=directory owner=root group=root mode=0755

- name: Check existence of swap file
  stat: path=/swap/swapfile
  register: swapfile

- name: Allocate swap file
  when: not swapfile.stat.exists
  # See http://www.faqs.org/docs/linux_admin/x1762.html
  command: >-
    dd if=/dev/zero of=/swap/swapfile bs=1M count={{ ec2_swapper_swap_size }}

- name: Format swap file
  command: mkswap /swap/swapfile

- name: Ensure swap file permissions
  file: path=/swap/swapfile owner=root group=root mode=0600

- name: Enable swap
  command: swapon /swap/swapfile

- name: Ensure state of swap entry in /etc/fstab
  mount:
    name: none
    src: /swap/swapfile
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
