---

# to run this playbook, make sure s3cmd >= 1.5 is installed on your machine
#
# Usage:
# ansible-playbook -i local/inventory/localhost
#    playbooks/deploy_openebooks_local.yml --extra-vars="level=staging"
# ansible-playbook -i local/inventory/localhost
#    playbooks/deploy_openebooks_local.yml --extra-vars="level=production"

- hosts: 127.0.0.1
  connection: local

- name: Deploy OpenEbooks.net from local host
  hosts: 127.0.0.1
  connection: local
  sudo: False
  tasks:
    - include: ../roles/openebooks/tasks/deploy.yml
  vars_files:
    - "../vars/{{ level }}.yml"
    - "../roles/openebooks/defaults/main.yml"
    - "../roles/openebooks/vars/{{ level }}.yml"
    - "../roles/openebooks/vars/local.yml"
