---

# To run standalone, specify
# --extra-vars "level=<development|staging|production>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: Gather inventory facts in case playbook is run standalone
  hosts: all


- name: PostgreSQL databases
  hosts: postgresql_dbs
  become: yes
  roles:
    - postgresql
