---

# Configuration for development VMs.

# For first-time initialization:
#   - run this with --extra-vars "initial_run=true"
#     to prevent an error with Elasticsearch shard replication.
#   - See the comment in playbooks/siteproxy.yml regarding
#     the loadbalancer health check.

- include: playbooks/common.yml level=development ingestion2=true

- name: Configure dev1 as Munin master for development
  hosts: dev1
  roles:
    - munin_master
    - monitoring_web
  vars:
    level: development
    ingestion2: true
  sudo: yes

- include: playbooks/dev_loadbalancer.yml ingestion2=true

- include: playbooks/elasticsearch.yml level=development ingestion2=true

- include: playbooks/postgresql.yml level=development

- include: playbooks/memcached.yml level=development

- name: Web Configuration (frontend and site)
  hosts: webapps
  sudo: yes
  roles:
    - common_web
    - common_sitenode
    - site_proxy
    - frontend
  vars:
    level: development
    ingestion2: true
    skip_configuration: false
    do_deployment: true

- name: Web Configuration (ingestion app and marmotta)
  # Technically, it's not necessary to specify marmotta because ingestion_app and
  # marmotta are the same in this environment, but this is done to be throrough.
  hosts:
    - ingestion_app
    - marmotta
  sudo: yes
  roles:
    - common_web
  vars:
    level: development
    ingestion2: true

- include: >-
    playbooks/api.yml level=development ingestion2=true

- include: playbooks/redis.yml level=development

- include: playbooks/tomcat.yml level=development

- include: playbooks/solr.yml level=development

- include: playbooks/marmotta.yml level=development

- include: playbooks/ingestion_app.yml level=development
