---

- name: Make sure that the "ingestion" user exists
  user:
    name: ingestion
    comment: "DPLA ingestion user"
    home: /home/ingestion
    shell: /bin/bash
    state: present

- name: Ensure existence of /v1
  file: path=/v1/ingestion state=directory

- name: "Ensure existence, ownership, and permissions of /v1/ingestion"
  file:
    path: /v1/ingestion
    state: directory
    owner: ingestion
    group: ingestion
    recurse: yes

- name: Ensure that Python dependencies are installed
  # Most of these are necessary for building Python with pyenv, and g++ is
  # included under the assumption that some module may need it
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - git
    - gcc
    - g++
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - llvm

- name: Ensure that pyenv is installed for 'ingestion' account
  become_user: ingestion
  script: >-
    ../../../files/install_python_tools.sh 2.7.13

- name: Ensure that the latest version of the AWS CLI is installed
  become_user: ingestion
  script: >-
    ../../../files/install_aws_cli.sh 2.7.13

- name: Ensure state of AWS CLI configuration directory
  file:
    path: /home/ingestion/.aws
    state: directory
    owner: ingestion
    group: ingestion
    mode: 0750

- name: Ensure state of AWS CLI configuration file
  template:
    src: ../../../templates/aws_config.j2
    dest: /home/ingestion/.aws/config
    owner: ingestion
    group: ingestion
    mode: 0600

- name: Ensure state of s3cmd configuration file
  copy:
    src: ../../../files/dot.s3cmd
    dest: /home/ingestion/.s3cmd
    owner: ingestion
    group: ingestion
    mode: 0600
